In [1]:
import numpy as np 

In [14]:
#Task 1 Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”​
my_file1 = open("Numbers.txt", "w")
first = int(input("Number 1"))
second = int(input("Number 2"))
third = int(input("Number 3"))
fourth = int(input("Number 4"))
lst = [first, second, third, fourth] 
my_file1.write(str(lst))
my_file1.write("\n")

my_file1.close()


In [21]:
# Task 2 Write a program to ask a student for their percentage mark and convert this to a grade.​

def mark_grade(grade):
    grade = int(input("What % did you get?"))

    if grade >= 70 and grade <=100:
        print("First-Class Degree") 
    elif grade <=69 and grade >= 60:
        print("Upper Second-Class Degree")
    elif grade <=59 and grade >= 50:
        print("Lower Second-Class Degree")
    elif grade <=49 and grade >= 40:
        print("Third Class Degree")
    else: 
        print("fail")   
    return grade

mark_grade(70)

First-Class Degree


70

In [4]:
# 1. Create a 1D array of numbers from 0 to 9
array1 = np.arange(10)
print(array1)


[0 1 2 3 4 5 6 7 8 9]


In [27]:
# Create a 3×3 NumPy array of all Boolean value Trues
matrix = np.ones((1, 9), dtype=bool).reshape(3,3)

print(matrix)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [29]:
# Extract all odd numbers from array of 1-10
a = np.arange(10)
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [30]:
#Replace all odd numbers in an array of 1-10 with the value -1​

replaced = a[a % 2 == 1] -1
print(replaced)


[0 2 4 6 8]


In [35]:
# Convert a 1D array to a 2D array with 2 rows​
a = np.arange(6)
b = np.reshape(a, (-1,2))
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [45]:
# Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals
a = np.arange(1,11)
b = np.arange(11,21)
c = np.column_stack((a,b))


sum1 = np.sum(c)
sum2 = np.dot(a,b)

print(c)
print(sum1)
print(sum2)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]
210
935
